FROM python:3.11

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all app code into the container
COPY . .

# Document the port used by frontend
EXPOSE 8050

# Start the Dash application

# TODO: Replace this with the right command
CMD ["???"]
