services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"      # S3 API
      - "9001:9001"      # Console UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio-data:

